{
    'name': 'Nexo Dealer',
    'version': '18.0.8.0.0',
    'summary': 'Gestión de concesionario de vehículos',
    'category': 'Sales',
    'depends': ['nexo_core', 'fleet', 'crm', 'hr', 'repair', 'sale', 'purchase', 'stock', 'product', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/nexo_sequence_data.xml',
        'data/nexo_cron_data.xml',

        'views/nexo_vehicle_brand_views.xml',
        'views/nexo_vehicle_model_views.xml',
        'views/nexo_vehicle_views.xml',
        'views/nexo_inventory_views.xml',
        'views/nexo_service_order_views.xml',
        'views/nexo_vehicle_history_views.xml',
        'views/nexo_crm_views.xml',
        'views/nexo_hr_views.xml',
        'views/nexo_sale_order_views.xml',
        'views/nexo_purchase_views.xml',
        'views/nexo_purchase_request_views.xml',
        'views/nexo_finance_views.xml',
        'views/nexo_notify_views.xml',
        'views/nexo_menus.xml',
        'views/nexo_dashboard_views.xml',
        'views/nexo_quick_sale_views.xml',
        'report/nexo_quotation_report.xml',
        'report/nexo_commission_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'nexo_dealer/static/src/js/nexo_dashboard.js',
            'nexo_dealer/static/src/xml/nexo_dashboard.xml',
            'nexo_dealer/static/src/scss/nexo_dashboard.scss',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'web_icon': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><circle cx='32' cy='32' r='28' fill='none' stroke='%23714BDF' stroke-width='5'/><path d='M32 12 L32 32 L44 38' fill='none' stroke='%23714BDF' stroke-width='5' stroke-linecap='round' stroke-linejoin='round'/><circle cx='32' cy='32' r='4' fill='%23714BDF'/></svg>",
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
