{
    'name': 'Dashboard',
    'version': '18.0.2.1.0',
    'summary': 'Gestión completa de concesionario de vehículos',
    'category': 'Sales',
    'depends': ['nexo_core', 'mail', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/nexo_email_templates.xml',
        'data/nexo_sequence_data.xml',
        'data/nexo_dashboard_data.xml',
        'data/nexo_cron_data.xml',
        'views/nexo_vehicle_brand_views.xml',
        'views/nexo_vehicle_model_views.xml',
        'views/nexo_vehicle_views.xml',
        'views/nexo_vehicle_image_views.xml',
        'views/nexo_inventory_views.xml',
        'views/nexo_service_order_views.xml',
        'views/nexo_test_drive_views.xml',
        'views/nexo_trade_in_views.xml',
        'views/nexo_vehicle_history_views.xml',
        'views/nexo_calendar_views.xml',
        'views/nexo_dashboard_views.xml',
        'views/nexo_sale_order_views.xml',
        'views/nexo_crm_views.xml',
        'views/nexo_hr_views.xml',
        'views/nexo_purchase_views.xml',
        'views/nexo_parts_views.xml',
        'views/nexo_finance_views.xml',
        'views/nexo_notify_views.xml',
        'views/nexo_menus.xml',
        'report/nexo_sale_order_report.xml',
        'report/nexo_service_order_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'nexo_dealer/static/src/js/nexo_dashboard_render.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
